MOBILE-3862: Update plugins documentation
moodlemobile/devdocs pull request #26
Opened 2024-04-29 14:56 UTC by NoelDeMartin

This PR is a rewrite of the plugins documentation, so rather than looking at the diff I'd suggest looking at the preview of the rendered HTML. You can find it here: https://noeldemartin.github.io/moodledevdocs/

The pages that have been rewritten are the ones under "Plugins development guide", even though some references and related content has been updated as well.

2024-05-03 08:45 UTC, dpalou requested changes

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/index.md
> +| `strftimetime`          | `h[:]mm[ ]A`                            | 4:28 PM                          |
One thing to take into account here is that some values can change depending on the language. For example in English `strftimetime` is "4:28 PM", but in Spanish it's "16:48". IMO it'd be nice to add some note explaining this.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +- `updateContent(args: Record<string, unknown>, component?: string, method?: string)`: Refresh the current page with new content. If `component` and `method` aren't provided, it will use the same as
This section is outdated, there are a couple of missing params in openContent and updateContent, and there are 2 new functions for plugins:

- updateModuleCourseContent(cmId: number, alreadyFetched?: boolean): update the content for a certain module in the course page. Only if that module is a site plugin using coursepagemethod. 

- updateCachedContent(): available from 4.4 version of the app. Updates in background the data cached by the app, without the user noticing it. It's similar to refreshContent but without reloading the template in the DOM, it only affects the data stored in the app for the following usages.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `displayopeninbrowser` | `true`   | Whether the module should display the "Open in browser" option in the top-right menu. <br /> <br /> This can also be configured in JavaScript with `this.displayO
This will change in the 4.4 version of the app. I think that now we'll only display the "open in browser" button for teachers, not for students (for all activities, not just site plugins).

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +#### CoreSettingsDelegate
This header has a wrong size, I think it should be "###".

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +Add support for a custom filter.
In here I would add that this is only needed if your filter needs to perform some transformations using Javascript code (e.g. MathJax filter). The filters that do all processing in PHP before the content is rendered won't need to adapt the plugin to the app, because the app will receive the content already treated (e.g. glossary auto-link filter).

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `componentId` | -               | Component ID for contextual functionality, such as filters. |
I think it would be better to say that it's used when downloading files instead of filters. These properties are passed to filters, but right now in filters they're only used for file downloads too.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `maxHeight`   | -               | Max height in pixels to render the content box. The minimum accepted value is 50. Using this parameter will force `display: block` to calculate the height better.
This section is outdated too. The maxHeight property no longer exists, now this behaviour is achieved by using the collapsible-item directive.

And now there are a bunch of new inputs and outputs: highlight, filter, contextLevel + contextInstanceId (used to determine which filters to apply), courseId, wsNotFiltered, captureLinks, openLinksInApp, hideIfEmpty, disabled, afterRender, onClick.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `hidden` | -       | When this attribute is present, with any value, all the buttons are hidden. |
We also support the "prepend" attribute. If set, buttons will be added at the beginning, otherwise they're added at the end.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `canDownload`       | `true`   | Whether file can be downloaded. |
This section is missing showSize, showTime and onDelete.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `autoLogin` | `'check'` | Whether to open the link with auto-login. Possible values are `yes`, `no`, and `check` (Auto-login only if the link belongs to the current site) |
showBrowserWarning is missing.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `form`         | -        | ID or name to identify a form in the template, that will be obtained from `document.forms`. The form data will be included in the arguments for the new page request. <br
Missing the following inputs: jsData, preSets, ptrEnabled.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/api-reference.md
> +| `newContentPreSets` | -        | Additional configuration for the Web Service request for the new page. You can find the available options in the [CoreSiteWSPreSets type declaration](https://github
Missing ptrEnabled input.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/examples/course-formats.md
> +                <core-course-module text-wrap [module]="module" [section]="section" (completionChanged)="onCompletionChange()">
The 2 "text-wrap" attributes in this example are no longer needed. There are 3 more in other places.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/examples/forms.md
> +This could also be done without using `otherdata`, using the `form` input of the `core-site-plugins-call-ws` directive. But we wouldn't be able to set a default value:
I think the last sentence isn't true. You can still use ngModel and otherdata with this approach, but then you don't use the variable to send the data, you get it from the form.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/examples/forms.md
> +However, as we pointed out before, using this approach you won't be able to set an initial value. It's up to you to decide which approach to take with the given trade-offs.
As above, you can initialize the control and set the initial value, but then don't use it to send the data.

2024-05-03 08:45 UTC, dpalou commented on general/app/development/plugins-development-guide/examples/forms.md
> +public static function execute_returns(): external_description {
Shouldn't this be execute_parameters instead of execute_returns?

2024-05-07 06:06 UTC, dpalou approved these changes, later dismissed

2024-05-07 06:50 UTC, dpalou approved these changes

2024-05-07 10:09 UTC, crazyserver approved these changes

2024-05-08 07:22 UTC, alfonso-salces approved these changes

2024-05-31 11:03 UTC, jleyva approved these changes

2024-05-31 11:04 UTC, merged